### ISSUE TITLE
Progress bar for page every load

### ISSUE THREAD

**Issue by imsaptarshi** [Orbits-Inc/orbits#21]
Example 
![Screenshot_20210608_215901](https://user-images.githubusercontent.com/65108480/121223103-d180c100-c8a4-11eb-9f9d-9f00b81bcff4.png)

**Comment by AadityaMunjal** [comment]
@imsaptarshi We can use [nprogress](https://github.com/rstacruz/nprogress)

**Comment by RajvirSingh1313** [comment]
I can try it out locally if it worked then I will make pull request
